--CONTEXTO TODOS OS ORDER_STORE QUE SÃO IGUAL A -100 SIGINIFICA QUE FORAM COMPRADAS ONLINE.
--E OS NÚMEROS POSITIVOS SÃO ME LOJAS FISICAS.





--AQUI SELECIONEI NA MINHA TABELA TODAS AS COMPRAS FEITAS ONLINE.
--SELECT * 
--FROM pedidos
--WHERE order_store = -100
--LIMIT 5000



--E AQUI ESTOU FILTRANDO TODAS AS COMPRAS QUE FORAM REALIZADAS EM LOJAS DA REDE.
SELECT *
FROM pedidos
WHERE order_store <> -100 -- <> diferente de
LIMIT 10

--ENTÃO APRENDIZADO DESSE CODE, É QUE <> SIGINIFICA DIFERENTE DE.
--RESOLVERIA COLOCANDO > -100 NESSE CASO IA DAR BOM, MAS PENSEI QUE PODERIA EM OUTROS CASOS PEGAR -99 -89.