-- IN
-- USAMOS IN COM WHERE, PARA VERIFICAR SE UM VALOR CORRESPONDE COM UM VALOR DA LISTA
/*
SELECT COLUNA
FROM TABELA
WHERE COLUNA IN(VALUE1,VALUE2)

EX:
SE EU QUISESSE SELECIONAR TODOS OS CLIENTES DE UMA TABELA QUE VIVEM EM NOVA YORK OU LOS ANGELES USARIA DE ASSIM:

SELECT *
FROM LOJA.CLIENTE
WHERE CITY IN('NEW YORK,'LOS ANGELES');

ISSO RETORNARIA TODOS OS CLIENTES QUE ESTÃO LOCALIZADOS EM NOVA YORK OU LOS ANGELES.
POSSO ESPECIFICAR UMA LISTA DE VALORES, EM VEZ DE USAR VÁRIOS OPERADORES 'OR'


*/

SELECT *
FROM Person.Person
WHERE BusinessEntityID IN (2,7,13)
--USANDO O NOT IN
SELECT *
FROM Person.Person
WHERE BusinessEntityID NOT IN (2,5,13);

--AQUI RESOLVENDO COM BETWEEN, MAS TEM SUAS LIMITAÇÕES, PORQUE PODERIA SER NÃO LINEAR
SELECT *
FROM Person.Person
WHERE BusinessEntityID BETWEEN 1 AND 12