--DESAFIO NIVEL MAIOR
/*
QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS QUE 1500 DOLARES?
*/

SELECT COUNT(listPrice)
FROM Production.Product
WHERE ListPrice > 1500
/*
1-PRIMEIRO VI O PANORAMA TOTAL
2-O NOME DA COLUNA TEM O NOME listPrice
3-SELECIONEI E PEDI PARA CONTAR O LISTPRICE
4-CRIEI UMA CONDIÇÃO, OU SEJA SÓ CONTAR PRODUTOS QUE TENHAM VALOR ACIMA DE 1500
*/

--SEGUNDO DESAFIO
--QUANTAS PESSOAS TEMOS COM SOBRENOME QUE INICIA COM A A LETRA P?

SELECT COUNT(LastName)
FROM Person.Person
WHERE LastName LIKE 'P%'

--DESAFIO 3
-- EM QUANTAS CIDADES ÚNICASESTÃO CADASTRADOS NOSSOS CLIENTES?

SELECT COUNT (DISTINCT City)
FROM Person.Address
--A opção DISTINCT é usada para eliminar os valores duplicados antes de fazer a contagem. 
-- ignora cidades duplicadas

--DESAFIO 4
-- QUAIS SÃO AS CIDADES ÚNICAS QUE TEMOS CADASTRADAS EM NOSSO SISTEMA?

SELECT DISTINCT (city)
from Person.Address

--DESAFIO 5
-- QUANTOS PRODUTOS DE COR VERMELHA TEM O PREÇO ENTRE 500 A 1000 DOLARES

SELECT COUNT(ProductID)
FROM Production.Product
WHERE Color LIKE 'RED' AND ListPrice BETWEEN 500 AND 1000;

SELECT COUNT(*)
FROM Production.Product
WHERE Name like '%Road%'