--HORA DO DESAFIO

-- 1- PRECISO SABER QUANTAS PESSOAS TEM O MESMO MIDDLENAME AGRUPADAS POR O MIDDLENAME

SELECT MiddleName, COUNT(FirstName) AS 'QNT'
FROM Person.Person
GROUP BY MiddleName

-- 2- PRECISO SABER A QUANTIDADE QUE CADA PRODUTO É VENDIDO NA LOJA.

SELECT ProductID, COUNT(OrderQty) AS 'VENDAS'
FROM Sales.SalesOrderDetail
GROUP BY ProductID


SELECT ProductID, AVG(OrderQty) AS 'VENDAS'
FROM Sales.SalesOrderDetail
GROUP BY ProductID

-- 3- PRECISO SABER O TOP 10 VENDAS, COM O MAIOR VALOR DE VENDA POR PRODUTO DE MANEIRA DESC

SELECT TOP 10 ProductID, SUM(LineTotal) AS 'TOTAL VENDA'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC;


SELECT ProductID, COUNT(ProductID) AS 'CONTAGEM',
AVG(OrderQty) AS 'MEDIA '
FROM Production.WorkOrder
GROUP BY ProductID
