/*
Cria grupo, subgrupos dentro dos nossos resultados das nossas consultas.

SELECT DEPARTAMENTO_ID, MAX(SALARIO)
FROM EMPREGADO
GROUP BY DEPARTAMENTO_ID
SE EU NÃO AGRUPASSE ELE ME RETORNARIA O SALARIO MAXIMO DA EMPRESA TODA, FAZENDO O GROUP POR DEPARTAMENTO_ID, ELE VAI AGRUPAR OS SALARIO MAXIMOS POR
DEPARTAMENTO.
*/

SELECT *
FROM Sales.SalesOrderDetail 

SELECT SpecialOfferID, SUM(UnitPrice)
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
/*
ELE FOI NO BANCO E PEGOU TODAS OS ID 9 E ONDE TEM UM VALOR DE PREÇO UNITÁRIO E SOMOU TODOS OS VALORES
AGRUPOU INFORMAÇÕES, SOMOU TODOS OS VALORES E AGRUPOU POR ID.
*/
SELECT SpecialOfferID,UnitPrice
FROM Sales.SalesOrderDetail
WHERE SpecialOfferID = 9
-- ASSIM ELE PERCORRE TODO MEU CÓDIGO E VERIFICA 

--VAMOS DIZER QUE EU QUERO SABER QUANTOS CADA PRODUTO FOI VENDIDO ATÉ HOJE

SELECT ProductID, COUNT(ProductID) as 'Quantidade venda'
FROM Sales.SalesOrderDetail
Group by ProductID
/*
AGRUPOU TODOS OS PRODUTOS COM ID 707, E CONTOU QUANTAS VEZES ELE APARECE NO MEU BANCO DE DADOS.
OU SEJA O ID 707 APARECE 3083 VEZES NA MINHA TABELA
*/

--DESAFIO
--QUANTOS NOMES DE CADA NOME TEMOS NO CADASTRO
--EXEMPLO QUANTOS KEN, KAREN, LEON, PIETRA TEMOS
SELECT FirstName, COUNT(FirstName) AS 'QNT NOMES'
FROM Person.Person
GROUP BY FirstName
--EXEMPLO GUSTAVO FOI REGISTRADO DOIS GUSTAVOS NA MINHA TABELA PERSON.


-- NA TABELA PRODUCTION.PRODUCT EU QUERO SABER A MÉDIA DE PREÇO PARA OS PRODUTOS QUE SÃO PRATAS.
SELECT Color, AVG(ListPrice) 'PREÇO'
FROM Production.Product
GROUP BY Color

SELECT Color, AVG(ListPrice) 'PREÇO'
FROM Production.Product
WHERE Color = 'silver'
GROUP BY Color